# -*- coding: utf-8 -*-
"""Sinh industry-mapping.md và .json — CHỦ SỞ HỮU DUY NHẤT của bảng map ngành.

Sửa nội dung thì sửa TRONG FILE NÀY rồi chạy lại, cấm sửa tay hai file sinh ra.
Cùng khuôn với gen_field_selection.py.

    python docs/20-design/gen_industry_mapping.py
"""
import json
import os

DO_NGAY = '2026-08-27'
NL = chr(10)

# 24 ngành level 2 — tên và code do industry-tree.md §2 sở hữu, chép ở đây để script tự đủ.
INDUSTRIES = [
    ('NGANHANG', 'Ngân hàng và Tín dụng'),
    ('CHUNGKHOAN', 'Công ty Chứng khoán'),
    ('BAOHIEM', 'Kinh doanh Bảo hiểm'),
    ('DANDUNG', 'Bất động sản Dân dụng'),
    ('KHUCONGNGHIEP', 'Bất động sản Khu công nghiệp'),
    ('XAYDUNG', 'Thi công Xây dựng'),
    ('VATLIEU', 'Vật liệu Xây dựng'),
    ('KIMLOAI', 'Kim loại Công nghiệp'),
    ('KHOANGSAN', 'Than và Khoáng sản'),
    ('HOACHAT', 'Hóa chất và Phân bón'),
    ('NHUA', 'Nhựa, Bao bì và Giấy'),
    ('THIETBI', 'Thiết bị Điện và Máy móc'),
    ('NONGNGHIEP', 'Nông nghiệp và Chăn nuôi'),
    ('THUYSAN', 'Chế biến Thủy sản'),
    ('DETMAY', 'Dệt may, Gỗ và Gia dụng'),
    ('CAOSU', 'Cao su và Săm lốp'),
    ('BANLE', 'Bán buôn và Bán lẻ'),
    ('THUCPHAM', 'Thực phẩm và Đồ uống'),
    ('DULICH', 'Hàng không, Du lịch và Truyền thông'),
    ('YTE', 'Y tế, Giáo dục và Xuất bản'),
    ('TIENICH', 'Điện, Nước và Môi trường'),
    ('DAUKHI', 'Dầu mỏ và Khí đốt'),
    ('VANTAI', 'Vận tải, Cảng biển và Kho bãi'),
    ('CONGNGHE', 'Công nghệ Thông tin và Viễn thông'),
]

# Tên nhánh ICB — sự thật đo từ getAllIcbIndustry, không diễn giải.
ICB_L3_NAME = {
    '2350': ('Xây dựng và Vật liệu', 'Xây dựng và Vật liệu'),
    '8630': ('Bất động sản', 'Bất động sản'),
    '2770': ('Vận tải', 'Hàng & Dịch vụ Công nghiệp'),
    '3570': ('Sản xuất thực phẩm', 'Thực phẩm và đồ uống'),
    '7570': ('Nước & Khí đốt', 'Điện, nước & xăng dầu khí đốt'),
    '1350': ('Hóa chất', 'Hóa chất'),
    '2790': ('Tư vấn & Hỗ trợ Kinh doanh', 'Hàng & Dịch vụ Công nghiệp'),
    '3760': ('Hàng cá nhân', 'Hàng cá nhân & Gia dụng'),
    '7530': ('Sản xuất & Phân phối Điện', 'Điện, nước & xăng dầu khí đốt'),
    '4570': ('Dược phẩm', 'Y tế'),
    '8770': ('Dịch vụ tài chính', 'Dịch vụ tài chính'),
    '5750': ('Du lịch & Giải trí', 'Du lịch và Giải trí'),
    '1750': ('Kim loại', 'Tài nguyên Cơ bản'),
    '3530': ('Bia và đồ uống', 'Thực phẩm và đồ uống'),
    '1770': ('Khai khoáng', 'Tài nguyên Cơ bản'),
    '2750': ('Công nghiệp nặng', 'Hàng & Dịch vụ Công nghiệp'),
    '5550': ('Truyền thông', 'Truyền thông'),
    '8350': ('Ngân hàng', 'Ngân hàng'),
    '2720': ('Hàng công nghiệp', 'Hàng & Dịch vụ Công nghiệp'),
    '8980': ('Quỹ đầu tư', 'Dịch vụ tài chính'),
    '2730': ('Điện tử & Thiết bị điện', 'Hàng & Dịch vụ Công nghiệp'),
    '5370': ('Bán lẻ', 'Bán lẻ'),
    '1730': ('Lâm nghiệp và Giấy', 'Tài nguyên Cơ bản'),
    '3350': ('Ô tô và phụ tùng', 'Ô tô và phụ tùng'),
    '9570': ('Thiết bị và Phần cứng', 'Công nghệ Thông tin'),
    '8530': ('Bảo hiểm phi nhân thọ', 'Bảo hiểm'),
    '9530': ('Phần mềm & Dịch vụ Máy tính', 'Công nghệ Thông tin'),
    '4530': ('Thiết bị và Dịch vụ Y tế', 'Y tế'),
    '0570': ('Thiết bị, Dịch vụ và Phân phối Dầu khí', 'Dầu khí'),
    '3720': ('Hàng gia dụng', 'Hàng cá nhân & Gia dụng'),
    '6530': ('Viễn thông cố định', 'Viễn thông'),
    '3780': ('Thuốc lá', 'Hàng cá nhân & Gia dụng'),
    '5330': ('Phân phối thực phẩm & dược phẩm', 'Bán lẻ'),
    '6570': ('Viễn thông di động', 'Viễn thông'),
    '0530': ('Sản xuất Dầu khí', 'Dầu khí'),
    '3740': ('Hàng hóa giải trí', 'Hàng cá nhân & Gia dụng'),
    '8570': ('Bảo hiểm nhân thọ', 'Bảo hiểm'),
    '0580': ('Năng lượng thay thế', 'Dầu khí'),
    '2710': ('Hàng không & Quốc phòng', 'Hàng & Dịch vụ Công nghiệp'),
    '8670': ('Quỹ ủy thác BĐS', 'Bất động sản'),
}
ICB_L4_NAME = {
    '8985': 'Quỹ đầu tư',
    '2799': 'Chất thải & Môi trường',
    '3765': 'Giầy dép',
    '1353': 'Nhựa, cao su & sợi',
    '1771': 'Khai thác Than',
    '3573': 'Nuôi trồng nông & hải sản',
    '8777': 'Môi giới chứng khoán',
    '3763': 'Hàng May mặc',
    '8633': 'Bất động sản',
    '8355': 'Ngân hàng',
    '6575': 'Viễn thông di động',
    '8536': 'Bảo hiểm phi nhân thọ',
    '2791': 'Tư vấn & Hỗ trợ KD',
    '1357': 'Sản phẩm hóa dầu, Nông dược & Hóa chất khác',
    '2353': 'Vật liệu xây dựng & Nội thất',
    '1733': 'Lâm sản và Chế biến gỗ',
    '1775': 'Khai khoáng',
    '2357': 'Xây dựng',
    '2777': 'Kho bãi, hậu cần và bảo dưỡng',
    '5557': 'Sách, ấn bản & sản phẩm văn hóa',
    '5555': 'Dịch vụ truyền thông',
    '5337': 'Phân phối thực phẩm',
    '3577': 'Thực phẩm',
    '4577': 'Dược phẩm',
    '2773': 'Vận tải Thủy',
    '2737': 'Thiết bị điện',
    '2797': 'Nhà cung cấp thiết bị',
    '4535': 'Thiết bị y tế',
    '7535': 'Sản xuất & Phân phối Điện',
    '4573': 'Công nghệ sinh học',
    '2723': 'Containers & Đóng gói',
    '2757': 'Máy công nghiệp',
    '7573': 'Phân phối xăng dầu & khí đốt',
    '5379': 'Phân phối hàng chuyên dụng',
    '5757': 'Nhà hàng và quán bar',
    '3533': 'Sản xuất bia',
    '3767': 'Hàng cá nhân',
    '1757': 'Thép và sản phẩm thép',
    '5753': 'Khách sạn',
    '7577': 'Nước',
    '3743': 'Điện tử tiêu dùng',
    '3537': 'Đồ uống & giải khát',
    '3726': 'Thiết bị gia dụng',
    '5759': 'Vận tải hành khách & Du lịch',
    '0533': 'Sản xuất và Khai thác dầu khí',
    '5373': 'Bán lẻ phức hợp',
    '8575': 'Bảo hiểm nhân thọ',
    '8637': 'Tư Vấn, Định giá, Môi giới Bất động sản',
    '1737': 'Sản xuất giấy',
    '2793': 'Đào tạo & Việc làm',
    '7575': 'Tiện ích khác',
    '9578': 'Thiết bị viễn thông',
    '3785': 'Thuốc lá',
    '1755': 'Kim Loại màu',
    '9533': 'Dịch vụ Máy tính',
    '9537': 'Phần mềm',
    '5377': 'Dịch vụ tiêu dùng chuyên ngành',
    '3357': 'Lốp xe',
    '3353': 'Sản xuất ô tô',
    '8771': 'Quản lý tài sản',
    '4537': 'Dụng cụ y tế',
    '5755': 'Dịch vụ giải trí',
    '2779': 'Dịch vụ vận tải',
    '2771': 'Chuyển phát nhanh',
    '8773': 'Tài chính cá nhân',
    '6535': 'Viễn thông cố định',
    '2753': 'Xe tải & Đóng tàu',
    '3355': 'Phụ tùng ô tô',
    '1777': 'Khai thác vàng',
    '3535': 'Vang & Rượu mạnh',
    '2733': 'Hàng điện & điện tử',
    '8775': 'Tài chính đặc biệt',
    '5751': 'Dịch vụ hàng không',
    '3722': 'Đồ gia dụng lâu bền',
    '9572': 'Phần cứng',
    '3747': 'Đồ chơi',
    '1753': 'Nhôm',
    '5553': 'Giải trí & Truyền thông',
    '0573': 'Thiết bị và Dịch vụ Dầu khí',
    '8538': 'Tái bảo hiểm',
    '2727': 'Công nghiệp phức hợp',
    '9535': 'Internet',
    '9574': 'Thiết bị văn phòng',
    '3724': 'Đồ gia dụng một lần',
    '4533': 'Chăm sóc y tế',
    '2775': 'Đường sắt',
}

# ---------------------------------------------------------------- LỚP 1
# Dòng cấp 3 = mặc định cho cả nhánh. Đủ 40/40 nhánh cấp 3 của cây ICB.
L3 = {
    '2350': ('XAYDUNG', 'nền của nhánh; vật liệu tách ở dòng 2353'),
    '8630': ('DANDUNG', 'gồm cả tư vấn/môi giới 8637; KCN ICB không tách → lớp 2'),
    '2770': ('VANTAI', 'cả 5 nhánh con đều là vận tải/kho bãi'),
    '3570': ('THUCPHAM', 'nền là chế biến 3577; nuôi trồng tách ở dòng 3573'),
    '7570': ('TIENICH', 'nền là nước 7577; xăng dầu-khí tách ở dòng 7573'),
    '1350': ('HOACHAT', 'nền là hóa dầu/nông dược 1357; nhựa-cao su tách ở 1353'),
    '2790': ('TIENICH', 'nền là môi trường đô thị 2799 — chủ dự án chốt 2026-08-27'),
    '3760': ('DETMAY', 'may mặc 47 + hàng cá nhân 8 + giày dép 2'),
    '7530': ('TIENICH', 'sản xuất & phân phối điện'),
    '4570': ('YTE', 'dược phẩm + công nghệ sinh học'),
    '8770': ('CHUNGKHOAN', 'nền là môi giới 8777; tín dụng tách ở 8775/8773'),
    '5750': ('DULICH', 'gồm 5751 dịch vụ hàng không — tên ngành đã có "Hàng không"'),
    '1750': ('KIMLOAI', 'thép + nhôm + kim loại màu'),
    '3530': ('THUCPHAM', 'bia + đồ uống + rượu'),
    '1770': ('KHOANGSAN', 'khai khoáng + than + vàng'),
    '2750': ('THIETBI', 'máy công nghiệp + đóng tàu'),
    '5550': ('YTE', 'nền là sách/ấn bản giáo dục 5557 — chốt 2026-08-27'),
    '8350': ('NGANHANG', ''),
    '2720': ('NHUA', 'nền là bao bì 2723; phức hợp tách ở 2727'),
    '8980': ('', 'KHÔNG NẠP — 24 chứng chỉ quỹ; ETF/quỹ không có ngành'),
    '2730': ('THIETBI', 'thiết bị điện + hàng điện tử'),
    '5370': ('BANLE', 'bán lẻ phức hợp + phân phối chuyên dụng'),
    '1730': ('DETMAY', 'nền là gỗ nội thất 1733 — giải luôn ca TTF/ACG/SAV; giấy tách ở 1737'),
    '3350': ('BANLE', 'nền là đại lý ô tô 3353, 6/7 mã HOSE là đại lý — chốt 2026-08-27; lốp tách ở 3357'),
    '9570': ('CONGNGHE', 'thiết bị viễn thông + phần cứng'),
    '8530': ('BAOHIEM', 'phi nhân thọ + tái bảo hiểm'),
    '9530': ('CONGNGHE', 'phần mềm + dịch vụ máy tính + internet'),
    '4530': ('YTE', 'thiết bị + dụng cụ + chăm sóc y tế'),
    '0570': ('DAUKHI', 'thiết bị và dịch vụ dầu khí'),
    '3720': ('DETMAY', 'hàng gia dụng — giải luôn ca GDT'),
    '6530': ('CONGNGHE', 'viễn thông cố định'),
    '3780': ('THUCPHAM', 'thuốc lá'),
    '5330': ('BANLE', 'phân phối thực phẩm & dược phẩm'),
    '6570': ('CONGNGHE', 'viễn thông di động'),
    '0530': ('DAUKHI', 'lọc dầu + phân phối (BSR, OIL, PLX)'),
    '3740': ('DETMAY', 'hàng hóa giải trí; điện tử tiêu dùng tách ở 3743'),
    '8570': ('BAOHIEM', 'bảo hiểm nhân thọ (BVH)'),
    '0580': ('TIENICH', 'Năng lượng thay thế — chưa có DN; ở VN là nhà phát điện tái tạo'),
    '2710': ('THIETBI', 'Hàng không & Quốc phòng — chưa có DN; là CHẾ TẠO máy bay, không phải hãng bay'),
    '8670': ('DANDUNG', 'Quỹ ủy thác BĐS — chưa có DN'),
}

# Dòng cấp 4 = ngoại lệ, THẮNG dòng cấp 3 cùng nhánh nhờ luật khớp-chính-xác-trước.
L4 = {
    '2353': ('VATLIEU', 'tách khỏi 2350 — vật liệu & nội thất'),
    '3573': ('THUYSAN', 'tách khỏi 3570 — thủy sản là đa số 29/45; 16 mã nông nghiệp bóc ở lớp 2'),
    '7573': ('DAUKHI', 'tách khỏi 7570 — xăng dầu & LPG, theo giá dầu (chốt 2026-08-27)'),
    '1353': ('NHUA', 'tách khỏi 1350 — nhựa/sợi; cao su thiên nhiên bóc ở lớp 2'),
    '2791': ('XAYDUNG', 'tách khỏi 2790 — tư vấn xây lắp điện (TV1-TV4, PPE, VNC)'),
    '2793': ('YTE', 'tách khỏi 2790 — đào tạo & việc làm'),
    '2797': ('THIETBI', 'tách khỏi 2790 — nhà cung cấp thiết bị'),
    '8775': ('NGANHANG', 'tách khỏi 8770 — tài chính đặc biệt'),
    '8773': ('NGANHANG', 'tách khỏi 8770 — tài chính tiêu dùng (EVF, F88)'),
    '1737': ('NHUA', 'tách khỏi 1730 — giấy & bao bì giấy (DHC, HHP)'),
    '3357': ('CAOSU', 'tách khỏi 3350 — săm lốp (CSM, DRC, SRC)'),
    '3355': ('THIETBI', 'tách khỏi 3350 — phụ tùng ô tô'),
    '5555': ('DULICH', 'tách khỏi 5550 — dịch vụ truyền thông'),
    '5553': ('DULICH', 'tách khỏi 5550 — giải trí & truyền thông (YEG, VNZ)'),
    '3743': ('THIETBI', 'tách khỏi 3740 — điện tử tiêu dùng'),
    '2727': ('THIETBI', 'tách khỏi 2720 — công nghiệp phức hợp'),
}

# ---------------------------------------------------------------- LỚP 2
# (mã, ngành, lý do). Gán tay đè lên lớp 1. ETL không bao giờ ghi bảng này.
OVERRIDE = [
    ('AAN', 'NONGNGHIEP', 'G3a nông nghiệp bóc khỏi 3573 sau khi đảo'),
    ('ACC', 'XAYDUNG', 'G5a xây lắp Bình Dương'),
    ('ACV', 'DULICH', 'G6 cảng hàng không tên ngành đã có Hàng không'),
    ('AFX', 'NONGNGHIEP', 'G3b B1'),
    ('AGM', 'NONGNGHIEP', 'G3b B1 lợi nhuận chạy theo giá nông sản'),
    ('AMS', 'XAYDUNG', 'G5d AMECC kết cấu thép công trình'),
    ('APC', 'NONGNGHIEP', 'G7 chiếu xạ nông sản thủy sản xuất khẩu CAN XAC NHAN'),
    ('AST', 'DULICH', 'G7 bán lẻ trong sân bay cùng luật với SCS'),
    ('BAF', 'NONGNGHIEP', 'G3a nông nghiệp bóc khỏi 3573 sau khi đảo'),
    ('BAX', 'KHUCONGNGHIEP', 'chủ KCN Bàu Xéo'),
    ('BCM', 'KHUCONGNGHIEP', '1a cả hai cùng KCN'),
    ('BDT', 'XAYDUNG', 'G5a xây lắp Đồng Tháp'),
    ('BIG', 'XAYDUNG', 'G3a BIG Invest Group đầu tư xây dựng ICB xếp sai'),
    ('BMP', 'NHUA', 'G5d Nhựa Bình Minh chạy theo giá hạt nhựa PVC'),
    ('BRC', 'CAOSU', 'G2 cao su thiên nhiên ICB xếp nhầm 1353'),
    ('BRR', 'CAOSU', 'G2 cao su thiên nhiên ICB xếp nhầm 1353'),
    ('CCL', 'KHUCONGNGHIEP', '1b theo chủ dự án'),
    ('CET', 'NONGNGHIEP', 'G3b B2'),
    ('CIA', 'DULICH', 'G6 dịch vụ sân bay Cam Ranh'),
    ('CIG', 'DANDUNG', 'G5b theo chủ dự án BĐS'),
    ('CMM', 'THUYSAN', 'G3a Camimex nằm ở 3577 nên vẫn cần đè'),
    ('CNA', 'NONGNGHIEP', 'G3a nông nghiệp bóc khỏi 3573 sau khi đảo'),
    ('CRE', 'KHUCONGNGHIEP', 'nguồn uy tín'),
    ('CSC', 'DANDUNG', 'G5b COTANA BĐS'),
    ('CTR', 'CONGNGHE', 'G5d Viettel Construction hạ tầng viễn thông và towerco'),
    ('CVN', 'XAYDUNG', 'G5d Vinam xây dựng dân dụng ICB xếp thiết bị y tế là sai'),
    ('D2D', 'KHUCONGNGHIEP', '1a cả hai cùng KCN'),
    ('DBC', 'NONGNGHIEP', 'G3a nông nghiệp bóc khỏi 3573 sau khi đảo'),
    ('DCV', 'DANDUNG', 'luật BCTC CT công ty quản lý quỹ không dùng mẫu BCTC CK'),
    ('DDB', 'DETMAY', 'G5d Đông Dương sản xuất sản phẩm từ gỗ'),
    ('DDG', 'TIENICH', 'G6 tra web cung cấp hơi nhiệt điện công nghiệp và nhiên liệu biomass'),
    ('DGT', 'XAYDUNG', 'G5a công trình giao thông'),
    ('DID', 'XAYDUNG', 'G5a xây lắp họ DIC'),
    ('DLG', 'DANDUNG', 'G5b Đức Long Gia Lai holding BĐS BOT'),
    ('DMN', 'NONGNGHIEP', 'G3a nông nghiệp bóc khỏi 3573 sau khi đảo'),
    ('DPR', 'KHUCONGNGHIEP', '1d ăn sóng BĐS KCN do chuyển đổi đất'),
    ('DQC', 'THIETBI', 'G7 Điện Quang sản xuất bóng đèn thiết bị chiếu sáng cùng luật với MBG'),
    ('DRG', 'CAOSU', 'G2 cao su thiên nhiên ICB xếp nhầm 1353'),
    ('DRH', 'KHUCONGNGHIEP', 'nguồn uy tín'),
    ('DRI', 'CAOSU', 'G2 cao su thiên nhiên ICB xếp nhầm 1353'),
    ('DTD', 'KHUCONGNGHIEP', '1b theo chủ dự án'),
    ('DTI', 'DANDUNG', 'G8 theo chủ dự án độ tin cậy thấp'),
    ('EIN', 'DANDUNG', 'G8 theo chủ dự án độ tin cậy thấp'),
    ('F88', 'BANLE', 'luật BCTC CT chuỗi cửa hàng cầm đồ'),
    ('FID', 'DANDUNG', 'luật BCTC com_type=CT không được vào CHUNGKHOAN holding có sàn BĐS'),
    ('FIT', 'DANDUNG', 'G8 F.I.T Group holding dược nước khoáng BĐS nông nghiệp'),
    ('FOC', 'CONGNGHE', 'G8 FPT Online quảng cáo trực tuyến và nội dung số'),
    ('GEL', 'DANDUNG', 'G5d chủ dự án chốt BĐS không xếp KCN'),
    ('GPC', 'NONGNGHIEP', 'G3b B2'),
    ('GSP', 'DAUKHI', 'G6 vận tải sản phẩm khí theo luật tên dầu khí'),
    ('GVR', 'KHUCONGNGHIEP', '1d ăn sóng BĐS KCN do chuyển đổi đất'),
    ('HAG', 'NONGNGHIEP', 'G3a nông nghiệp bóc khỏi 3573 sau khi đảo'),
    ('HAR', 'KHUCONGNGHIEP', '1b theo chủ dự án'),
    ('HHG', 'VANTAI', 'G7 Hoàng Hà xe khách tuyến cố định cùng luật với VNS'),
    ('HHS', 'DANDUNG', 'G7 Hoàng Huy nay là BĐS Hải Phòng'),
    ('HKB', 'NONGNGHIEP', 'G3b B1'),
    ('HMR', 'KHOANGSAN', 'G5a khai thác mỏ đá cùng luật với KSB và TTZ'),
    ('HNG', 'NONGNGHIEP', 'G3a nông nghiệp bóc khỏi 3573 sau khi đảo'),
    ('HPA', 'NONGNGHIEP', 'G3a nông nghiệp bóc khỏi 3573 sau khi đảo'),
    ('HPI', 'KHUCONGNGHIEP', 'nguồn uy tín'),
    ('HRC', 'CAOSU', 'G2 cao su thiên nhiên ICB xếp nhầm 1353'),
    ('HSL', 'NONGNGHIEP', 'G3b B1'),
    ('HVA', 'CONGNGHE', 'luật BCTC CT fintech cho vay ngang hàng'),
    ('IDC', 'KHUCONGNGHIEP', '1a cả hai cùng KCN'),
    ('IDV', 'KHUCONGNGHIEP', 'nguồn uy tín'),
    ('ILA', 'NONGNGHIEP', 'G3b B2'),
    ('IPA', 'DANDUNG', 'G5d luật BCTC com_type=CT holding mẹ của VND'),
    ('IRC', 'CAOSU', 'G2 cao su thiên nhiên ICB xếp nhầm 1353'),
    ('ITA', 'KHUCONGNGHIEP', 'nguồn uy tín'),
    ('KBC', 'KHUCONGNGHIEP', '1a cả hai cùng KCN'),
    ('KGM', 'NONGNGHIEP', 'G3b B1'),
    ('KOS', 'KHUCONGNGHIEP', '1b theo chủ dự án'),
    ('KPF', 'DANDUNG', 'luật BCTC com_type=CT holding đầu tư tài sản'),
    ('KSB', 'KHOANGSAN', 'G4 B mỏ đá thật'),
    ('L14', 'DANDUNG', 'G5b Licogi 14 BĐS và đầu tư'),
    ('LAI', 'DANDUNG', 'G5b theo chủ dự án'),
    ('LHG', 'KHUCONGNGHIEP', '1a cả hai cùng KCN'),
    ('LIX', 'HOACHAT', 'G7 bột giặt thực chất là hóa chất chủ dự án chốt'),
    ('MAC', 'VANTAI', 'G6 Macstar tiền thân cung ứng dịch vụ kỹ thuật hàng hải'),
    ('MBG', 'THIETBI', 'G5d sản xuất thiết bị chiếu sáng và thiết bị điện'),
    ('MH3', 'KHUCONGNGHIEP', 'tên là KCN'),
    ('MLS', 'NONGNGHIEP', 'G3a nông nghiệp bóc khỏi 3573 sau khi đảo'),
    ('NCG', 'NONGNGHIEP', 'G3a Anova Agri là thức ăn chăn nuôi và thú y'),
    ('NDF', 'NONGNGHIEP', 'G3b B1'),
    ('NET', 'HOACHAT', 'G7 bột giặt Net cùng luật với LIX'),
    ('NHA', 'DANDUNG', 'G5b Nhà và Đô thị Nam Hà Nội'),
    ('NHV', 'NONGNGHIEP', 'G3b B3'),
    ('NSC', 'NONGNGHIEP', 'G3a nông nghiệp bóc khỏi 3573 sau khi đảo'),
    ('NSS', 'NONGNGHIEP', 'G3a nông nghiệp bóc khỏi 3573 sau khi đảo'),
    ('NTC', 'KHUCONGNGHIEP', 'nguồn uy tín'),
    ('NTL', 'KHUCONGNGHIEP', 'nguồn uy tín'),
    ('NTP', 'NHUA', 'G5d Nhựa Tiền Phong'),
    ('OCH', 'DULICH', 'G3b chủ dự án chốt One Capital Hospitality đã xoay sang khách sạn'),
    ('OGC', 'DANDUNG', 'luật BCTC CT Đại Dương BĐS và khách sạn qua OCH'),
    ('PC1', 'TIENICH', 'G5c lợi nhuận chính từ thủy điện và điện gió'),
    ('PFL', 'DANDUNG', 'G5b Dầu khí Đông Đô BĐS'),
    ('PGN', 'HOACHAT', 'G7 phụ gia nhựa là hóa chất không phải nhựa'),
    ('PGT', 'DANDUNG', 'G6 tra web nay là holding M&A BĐS khách sạn không còn taxi'),
    ('PHR', 'KHUCONGNGHIEP', '1d ăn sóng BĐS KCN do chuyển đổi đất'),
    ('PLC', 'DAUKHI', 'G6 hóa dầu Petrolimex dầu nhờn nhựa đường'),
    ('PNJ', 'BANLE', 'G7 bán lẻ trang sức cả hai nguồn đồng ý'),
    ('PSL', 'NONGNGHIEP', 'G3a nông nghiệp bóc khỏi 3573 sau khi đảo'),
    ('PSP', 'DAUKHI', 'G6 cảng dịch vụ dầu khí'),
    ('PTB', 'VATLIEU', 'G5d Phú Tài đá granite theo chủ dự án'),
    ('PVM', 'DAUKHI', 'G6 máy thiết bị dầu khí'),
    ('PVO', 'DAUKHI', 'G6 dầu nhờn PV Oil'),
    ('PVP', 'DAUKHI', 'G6 nt'),
    ('PVT', 'DAUKHI', 'G6 nt lưu ý PVT là đội tàu chở dầu lớn nhất VN'),
    ('PVV', 'DAUKHI', 'G5d chủ dự án chốt theo tên Dầu khí'),
    ('PVX', 'DAUKHI', 'G5d chủ dự án chốt theo tên Dầu khí'),
    ('PXL', 'KHUCONGNGHIEP', 'tên là KCN'),
    ('RBC', 'CAOSU', 'G2 cao su thiên nhiên ICB xếp nhầm 1353'),
    ('RTB', 'CAOSU', 'G2 cao su thiên nhiên ICB xếp nhầm 1353'),
    ('SAS', 'DULICH', 'G7 SASCO bán lẻ sân bay Tân Sơn Nhất'),
    ('SBB', 'DETMAY', 'G3b chủ dự án chốt giữ phân loại cũ'),
    ('SBR', 'CAOSU', 'G2 cao su thiên nhiên ICB xếp nhầm 1353'),
    ('SBV', 'NHUA', 'G7 Siam Brothers dây thừng lưới đánh cá từ nhựa PP PE'),
    ('SGI', 'DANDUNG', 'G7 tra web holding sản xuất tài chính BĐS độ tin cậy thấp'),
    ('SHN', 'BANLE', 'G4 C HANIC thương mại VLXD và XNK mã than của ICB đã lỗi thời'),
    ('SIP', 'KHUCONGNGHIEP', '1a cả hai cùng KCN'),
    ('SKG', 'VANTAI', 'G6 tàu cao tốc chở khách'),
    ('SNZ', 'KHUCONGNGHIEP', 'nguồn uy tín'),
    ('SSC', 'NONGNGHIEP', 'G3a nông nghiệp bóc khỏi 3573 sau khi đảo'),
    ('STH', 'BANLE', 'G7 theo chủ dự án độ tin cậy thấp'),
    ('SVT', 'THIETBI', 'G4 B Savitech cơ khí chế tạo xe đạp xe máy phụ tùng'),
    ('SZB', 'KHUCONGNGHIEP', 'cùng họ Sonadezi'),
    ('SZC', 'KHUCONGNGHIEP', '1a cả hai cùng KCN'),
    ('SZG', 'KHUCONGNGHIEP', 'cùng họ Sonadezi'),
    ('SZL', 'KHUCONGNGHIEP', 'nguồn uy tín'),
    ('TAR', 'NONGNGHIEP', 'G3a nông nghiệp bóc khỏi 3573 sau khi đảo'),
    ('TCJ', 'NONGNGHIEP', 'G3a nông nghiệp bóc khỏi 3573 sau khi đảo'),
    ('TCO', 'VANTAI', 'G3a Janus Group tiền thân Vận tải Duyên Hải ICB xếp sai'),
    ('THG', 'XAYDUNG', 'G5a xây dựng Tiền Giang'),
    ('TID', 'KHUCONGNGHIEP', 'holding mẹ của TIP'),
    ('TIN', 'NGANHANG', 'luật BCTC com_type=NH lớp 1 đưa nhầm sang CHUNGKHOAN'),
    ('TIP', 'KHUCONGNGHIEP', '1a cả hai cùng KCN'),
    ('TIX', 'KHUCONGNGHIEP', 'nguồn uy tín'),
    ('TLD', 'XAYDUNG', 'G5a xây dựng đô thị Thăng Long'),
    ('TLG', 'YTE', 'G7 Thiên Long văn phòng phẩm giáo dục cùng mùa khai giảng CAN XAC NHAN'),
    ('TNC', 'CAOSU', 'G2 cao su thiên nhiên ICB xếp nhầm 1353'),
    ('TRC', 'CAOSU', 'G2 cao su thiên nhiên ICB xếp nhầm 1353'),
    ('TT6', 'NONGNGHIEP', 'G3b B1'),
    ('TTH', 'BANLE', 'G4 D thời trang Valentino và khoáng sản ICB xếp thép là sai'),
    ('TTZ', 'KHOANGSAN', 'G5d tra web khai thác cát đá sỏi Thái Bình'),
    ('TV1', 'TIENICH', 'G5c tư vấn thiết kế công trình điện theo chu kỳ đầu tư ngành điện'),
    ('TV2', 'TIENICH', 'G5c nt'),
    ('TV3', 'TIENICH', 'G5c nt danh sách cũ ghi THIETBI có vẻ nhầm'),
    ('TVC', 'DANDUNG', 'luật BCTC CT holding T Corp'),
    ('VC3', 'KHUCONGNGHIEP', 'nguồn uy tín'),
    ('VGC', 'KHUCONGNGHIEP', '1a cả hai cùng KCN dù ICB xếp vật liệu'),
    ('VHG', 'DANDUNG', 'G7 theo chủ dự án độ tin cậy thấp'),
    ('VIW', 'TIENICH', 'G5c VIWASEEN cấp nước'),
    ('VKC', 'NHUA', 'G2 thực chất cáp và ống nhựa không phải lốp'),
    ('VLC', 'NONGNGHIEP', 'G3a nông nghiệp bóc khỏi 3573 sau khi đảo'),
    ('VNS', 'VANTAI', 'G6 Vinasun taxi'),
    ('VRG', 'KHUCONGNGHIEP', 'tên là KCN'),
    ('VTK', 'CONGNGHE', 'G5d Tư vấn và Dịch vụ Viettel'),
    ('VTV', 'KHOANGSAN', 'G5a VICEM EE cấp 100% than cho 4 nhà máy xi măng thương mại theo mặt hàng'),
    ('VVS', 'THIETBI', 'G7 Đầu tư Phát triển Máy Việt Nam'),
    ('XMC', 'XAYDUNG', 'G5a xây dựng Xuân Mai'),
    ('XPH', 'HOACHAT', 'G7 Xà phòng Hà Nội cùng nhánh 3767 cùng luật'),
]

ISSUER_NAME = {
    'AAN': 'Công ty Cổ phần Lương thực A An',
    'ACC': 'Công ty Cổ phần Đầu tư và Xây dựng Bình Dương ACC',
    'ACV': 'Tổng Công ty Cảng Hàng không Việt Nam - CTCP',
    'AFX': 'Công ty Cổ phần Xuất Nhập khẩu Nông sản Thực phẩm An Giang',
    'AGM': 'Công ty Cổ phần Xuất nhập khẩu An Giang',
    'AMS': 'Công ty Cổ phần Cơ khí Xây dựng AMECC',
    'APC': 'Công ty Cổ phần Chiếu xạ An Phú',
    'AST': 'Công ty Cổ phần Dịch vụ Hàng không Taseco',
    'BAF': 'Công ty Cổ phần Nông nghiệp BAF Việt Nam',
    'BAX': 'Công ty Cổ phần Thống Nhất',
    'BCM': 'Tập đoàn Đầu tư và Phát triển Công nghiệp Becamex - CTCP',
    'BDT': 'Công ty Cổ phần Xây lắp và Vật liệu xây dựng Đồng Tháp',
    'BIG': 'Công ty Cổ phần Tập đoàn Đầu tư BIG',
    'BMP': 'Công ty Cổ phần Nhựa Bình Minh',
    'BRC': 'Công ty Cổ phần Cao su Bến Thành',
    'BRR': 'Công ty Cổ phần Cao su Bà Rịa',
    'CCL': 'Công ty Cổ phần Đầu tư và Phát triển Đô thị Dầu khí Cửu Long',
    'CET': 'Công ty Cổ phần HTC Holding',
    'CIA': 'Công ty Cổ Phần Dịch Vụ Sân Bay Quốc Tế Cam Ranh',
    'CIG': 'Công ty Cổ phần COMA 18',
    'CMM': 'Công ty Cổ phần Camimex',
    'CNA': 'Công ty Cổ phần Tổng công ty Chè Nghệ An',
    'CRE': 'Công ty Cổ phần Bất động sản Thế Kỷ',
    'CSC': 'Công ty Cổ phần Tập đoàn COTANA',
    'CTR': 'Tổng Công ty Cổ phần Công trình Viettel',
    'CVN': 'Công ty Cổ phần Vinam',
    'D2D': 'Công ty Cổ phần Phát triển Đô thị Công nghiệp số 2',
    'DBC': 'Công ty Cổ phần Tập đoàn Dabaco Việt Nam',
    'DCV': 'Công ty Cổ phần Quản Lý Quỹ đầu tư Dragon Capital Việt Nam',
    'DDB': 'Công ty Cổ Phần Thương Mại Và Xây Dựng Đông Dương',
    'DDG': 'Công ty Cổ phần Đầu tư Công nghiệp Xuất nhập khẩu Đông Dương',
    'DGT': 'Công ty Cổ phần Công trình Giao thông Đồng Nai',
    'DID': 'Công ty Cổ phần DIC - Đồng Tiến',
    'DLG': 'Công ty Cổ phần Tập đoàn Đức Long Gia Lai',
    'DMN': 'Công ty Cổ phần Domenal',
    'DPR': 'Công ty Cổ phần Cao su Đồng Phú',
    'DQC': 'Công ty Cổ phần Tập đoàn Điện Quang',
    'DRG': 'Công ty Cổ phần Cao su Đắk Lắk',
    'DRH': 'Công ty Cổ phần DRH Holdings',
    'DRI': 'Công ty Cổ phần Đầu tư Cao su Đắk Lắk',
    'DTD': 'Công ty Cổ phần Đầu tư Phát triển Thành Đạt',
    'DTI': 'Công ty Cổ phần Đầu tư Đức Trung',
    'EIN': 'Công ty Cổ phần Đầu tư - Thương Mại - Dịch vụ Điện lực',
    'F88': 'Công ty Cổ phần Đầu tư F88',
    'FID': 'Công ty Cổ phần Đầu tư và Phát triển Doanh nghiệp Việt Nam',
    'FIT': 'Công ty Cổ phần Tập đoàn F.I.T',
    'FOC': 'Công ty Cổ phần Dịch vụ Trực tuyến FPT',
    'GEL': 'Công ty Cổ phần Hạ tầng GELEX',
    'GPC': 'Công ty Cổ phần Tập đoàn Green+',
    'GSP': 'Công ty Cổ phần Vận tải Sản phẩm Khí Quốc tế',
    'GVR': 'Tập đoàn Công nghiệp Cao su Việt Nam - Công ty Cổ phần',
    'HAG': 'Công ty Cổ phần Hoàng Anh Gia Lai',
    'HAR': 'Công ty Cổ phần Đầu tư Thương mại Bất động sản An Dương Thảo Điền',
    'HHG': 'Công ty Cổ phần Hoàng Hà',
    'HHS': 'Công ty Cổ phần Đầu tư Dịch vụ Hoàng Huy',
    'HKB': 'Công ty Cổ phần Nông nghiệp và Thực phẩm Hà Nội - Kinh Bắc',
    'HMR': 'Công ty Cổ phần Đá Hoàng Mai',
    'HNG': 'Công ty Cổ phần Nông nghiệp Quốc tế Hoàng Anh Gia Lai',
    'HPA': 'Công ty Cổ phần Phát triển Nông nghiệp Hoà Phát',
    'HPI': 'Công ty Cổ phần Khu công nghiệp Hiệp Phước',
    'HRC': 'Công ty Cổ phần Cao su Hòa Bình',
    'HSL': 'Công ty Cổ phần Đầu tư Phát triển Thực phẩm Hồng Hà',
    'HVA': 'Công ty Cổ phần Đầu tư HVA',
    'IDC': 'Tổng Công ty IDICO - CTCP',
    'IDV': 'Công ty Cổ phần Phát triển Hạ tầng Vĩnh Phúc',
    'ILA': 'Công ty Cổ phần ILA',
    'IPA': 'Công ty Cổ phần Tập đoàn Đầu tư I.P.A',
    'IRC': 'Công ty Cổ phần Cao su Công nghiệp',
    'ITA': 'Công ty Cổ phần Đầu tư và Công nghiệp Tân Tạo',
    'KBC': 'Tổng Công ty Phát triển Đô thị Kinh Bắc - CTCP',
    'KGM': 'Công ty Cổ phần Xuất nhập khẩu Kiên Giang',
    'KOS': 'Công ty Cổ phần KOSY',
    'KPF': 'Công ty Cổ phần Đầu tư Tài sản KOJI',
    'KSB': 'Công ty Cổ phần Khoáng sản và Xây dựng Bình Dương',
    'L14': 'Công ty Cổ phần Licogi 14',
    'LAI': 'Công ty Cổ phần Đầu tư Xây dựng Long An IDICO',
    'LHG': 'Công ty Cổ phần Long Hậu',
    'LIX': 'Công ty Cổ phần Bột Giặt LIX',
    'MAC': 'Công ty Cổ phần Tập đoàn Macstar',
    'MBG': 'Công ty Cổ phần Tập đoàn MBG',
    'MH3': 'Công ty Cổ phần Khu công nghiệp Cao su Bình Long',
    'MLS': 'Công ty Cổ phần Chăn nuôi - Mitraco',
    'NCG': 'Công ty Cổ phần Đầu tư Anova Agri',
    'NDF': 'Công ty Cổ phần Chế biến thực phẩm nông sản xuất khẩu Nam Định',
    'NET': 'Công ty Cổ phần Bột giặt Net',
    'NHA': 'Tổng Công ty Đầu tư Phát triển Nhà và Đô thị Nam Hà Nội',
    'NHV': 'Công ty Cổ phần Sức khỏe Hồi sinh Việt Nam',
    'NSC': 'Công ty Cổ phần Tập đoàn Giống cây trồng Việt Nam',
    'NSS': 'Công ty Cổ phần Nông súc sản Đồng Nai',
    'NTC': 'Công ty Cổ phần Khu Công nghiệp Nam Tân Uyên',
    'NTL': 'Công ty Cổ phần Phát triển Đô thị Từ Liêm',
    'NTP': 'Công ty Cổ phần Nhựa Thiếu niên Tiền Phong',
    'OCH': 'Công ty Cổ phần One Capital Hospitality',
    'OGC': 'Công ty Cổ phần Tập đoàn Đại Dương',
    'PC1': 'Công ty Cổ phần Tập đoàn PC1',
    'PFL': 'Công ty Cổ phần Dầu khí Đông Đô',
    'PGN': 'Công ty Cổ phần Phụ Gia Nhựa',
    'PGT': 'Công ty Cổ phần PGT Holdings',
    'PHR': 'Công ty Cổ phần Cao su Phước Hòa',
    'PLC': 'Tổng Công ty Hóa dầu Petrolimex - Công ty Cổ phần',
    'PNJ': 'Công ty Cổ phần Vàng bạc Đá quý Phú Nhuận',
    'PSL': 'Công ty Cổ phần Chăn nuôi Phú Sơn',
    'PSP': 'Công ty Cổ phần Cảng Dịch vụ Dầu khí Đình Vũ',
    'PTB': 'Công ty Cổ phần Phú Tài',
    'PVM': 'Công ty Cổ phần Máy - Thiết bị Dầu khí',
    'PVO': 'Công ty Cổ phần Dầu nhờn PV Oil',
    'PVP': 'Công ty Cổ phần Vận tải Dầu khí Thái Bình Dương',
    'PVT': 'Tổng Công ty Cổ phần Vận tải Dầu khí',
    'PVV': 'Công ty Cổ phần Vinaconex 39',
    'PVX': 'Tổng Công ty Cổ phần Xây lắp Dầu khí Việt Nam',
    'PXL': 'Công ty Cổ phần Đầu tư Khu Công Nghiệp Dầu khí Long Sơn',
    'RBC': 'Công ty Cổ phần Công Nghiệp và Xuất nhập khẩu Cao Su',
    'RTB': 'Công ty Cổ phần Cao su Tân Biên',
    'SAS': 'Công ty Cổ phần Dịch vụ Hàng không Sân bay Tân Sơn Nhất',
    'SBB': 'Công ty Cổ phần Tập đoàn Bia Sài Gòn Bình Tây',
    'SBR': 'Công ty Cổ phần Cao su Sông Bé',
    'SBV': 'Công ty Cổ phần Siam Brothers Việt Nam',
    'SGI': 'Công ty Cổ phần Đầu tư SGI Holdings',
    'SHN': 'Công ty Cổ phần Đầu tư Tổng hợp Hà Nội',
    'SIP': 'Công ty Cổ phần Đầu tư Sài Gòn VRG',
    'SKG': 'Công ty Cổ phần Tàu Cao tốc Superdong - Kiên Giang',
    'SNZ': 'Tổng Công ty Cổ phần Phát triển Khu Công nghiệp',
    'SSC': 'Công ty Cổ phần Giống cây trồng Miền Nam',
    'STH': 'Công ty Cổ phần STH Holdings',
    'SVT': 'Công ty Cổ phần Công nghệ Sài Gòn Viễn Đông',
    'SZB': 'Công ty Cổ phần Sonadezi Long Bình',
    'SZC': 'Công ty Cổ phần Sonadezi Châu Đức',
    'SZG': 'Công ty Cổ phần Sonadezi Giang Điền',
    'SZL': 'Công ty Cổ phần Sonadezi Long Thành',
    'TAR': 'Công ty Cổ phần Nông nghiệp Công nghệ cao Trung An',
    'TCJ': 'Công ty Cổ phần Tô Châu',
    'TCO': 'Công ty Cổ phần Janus Group',
    'THG': 'Công ty Cổ phần Đầu tư và Xây dựng Tiền Giang',
    'TID': 'Công ty Cổ phần Tổng Công ty Tín Nghĩa',
    'TIN': 'Công ty Tài chính Tổng hợp cổ phần Tín Việt',
    'TIP': 'Công ty Cổ phần Phát triển Khu công nghiệp Tín Nghĩa',
    'TIX': 'Công ty Cổ phần Sản xuất Kinh doanh Xuất nhập khẩu Dịch vụ và Đầu tư Tân Bình',
    'TLD': 'Công ty Cổ phần Đầu tư Xây dựng và Phát triển Đô thị Thăng Long',
    'TLG': 'Công ty Cổ phần Tập đoàn Thiên Long',
    'TNC': 'Công ty Cổ phần Cao su Thống Nhất',
    'TRC': 'Công ty Cổ phần Cao su Tây Ninh',
    'TT6': 'Công ty Cổ Phần Tập Đoàn Tiến Thịnh',
    'TTH': 'Công ty Cổ phần Thương mại và Dịch vụ Tiến Thành',
    'TTZ': 'Công ty Cổ phần Đầu tư Xây dựng và Công nghệ Tiến Trung',
    'TV1': 'Công ty Cổ phần Tư vấn Xây dựng Điện 1',
    'TV2': 'Công ty Cổ phần Tư vấn Xây dựng Điện 2',
    'TV3': 'Công ty Cổ phần Tư vấn Xây dựng Điện 3',
    'TVC': 'Công ty Cổ phần Tập đoàn Quản lý tài sản T-Corp',
    'VC3': 'Công ty Cổ phần Tập đoàn Nam Mê Kông',
    'VGC': 'Tổng Công ty Viglacera - Công ty Cổ phần',
    'VHG': 'Công ty Cổ phần Đầu tư và Phát triển Việt Trung Nam',
    'VIW': 'Tổng công ty Đầu tư Nước và Môi trường Việt Nam - Công ty Cổ phần',
    'VKC': 'Công ty Cổ phần VKC Holdings',
    'VLC': 'Tổng Công ty Chăn nuôi Việt Nam - Công ty Cổ phần',
    'VNS': 'Công ty Cổ phần Ánh Dương Việt Nam',
    'VRG': 'Công ty Cổ phần Phát triển Đô thị và Khu Công nghiệp Cao Su Việt Nam',
    'VTK': 'Công ty Cổ phần Tư vấn và Dịch vụ Viettel',
    'VTV': 'Công ty Cổ phần Năng lượng và Môi trường VICEM',
    'VVS': 'Công ty Cổ phần Đầu tư Phát triển Máy Việt Nam',
    'XMC': 'Công ty cổ phần Đầu tư và Xây dựng Xuân Mai',
    'XPH': 'Công ty Cổ phần Xà phòng Hà Nội',
}


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    names = dict(INDUSTRIES)
    rows_l1 = []
    for code, (ind, note) in sorted(L3.items()):
        rows_l1.append(('L3', code, ICB_L3_NAME[code][0], ind, note))
    for code, (ind, note) in sorted(L4.items()):
        rows_l1.append(('L4', code, ICB_L4_NAME[code], ind, note))
    rows_l1.sort(key=lambda r: (r[1][:2], r[1]))

    m = ['# Bảng map ngành — ICB → 24 ngành riêng', '',
         '> ⚠️ **File này sinh tự động** từ [`gen_industry_mapping.py`](gen_industry_mapping.py). '
         'Sửa nội dung thì sửa trong script rồi chạy lại — **cấm sửa tay**. '
         'Bản máy đọc: [`industry-mapping.json`](industry-mapping.json).', '',
         f'**Trạng thái:** ✅ chốt {DO_NGAY}, chủ dự án duyệt từng nhóm chủ đề. '
         'File này là **chủ sở hữu duy nhất** của nội dung map; '
         '[industry-tree.md](industry-tree.md) sở hữu cây 24 ngành, không chép bảng này.', '',
         '## 1. Hai lớp', '',
         '| Lớp | Bảng | Ai ghi | Luật |', '|---|---|---|---|',
         '| **1 · máy** | `market.industry_icb_map` → `market.issuer.industry_id` | job `etl refdata`, mỗi lượt | '
         'khớp `icb_code` chính xác trước; không có thì leo `icb_code_path` lấy **tổ tiên gần nhất** |',
         '| **2 · tay** | `market.issuer_industry_override` | người, qua migration seed | ETL không đọc, không ghi |',
         '| **đọc** | view `market.v_issuer_industry` | — | `COALESCE(lớp 2, lớp 1)` |', '',
         'Vì luật phân giải leo từ dưới lên, **dòng cấp 4 thắng dòng cấp 3 cùng nhánh**, '
         'còn dòng cấp 3 làm lưới hứng cho mọi con cháu chưa có dòng riêng — kể cả mã ICB lá '
         'chưa từng xuất hiện. Đây là lý do bảng trộn hai cấp thay vì dùng cấp-4-thuần.', '',
         '🔴 **Cổ phiếu không có issuer thì không gán ngành.** Ngành gán ở doanh nghiệp, '
         'mã thừa hưởng — không có issuer thì không có hàng nào để gắn, ở cả hai lớp. '
         f'437 mã trong kho thuộc diện này *(đo {DO_NGAY})*, đều đã huỷ niêm yết.', '',
         '🔴 **Ba ngành tài chính khoá theo mẫu BCTC.** `com_type_code = NH` ⟺ `NGANHANG`, '
         '`CK` ⟺ `CHUNGKHOAN`, `BH` ⟺ `BAOHIEM` — ràng buộc hai chiều, không ngoại lệ. '
         'Ba nhóm này là ba **biểu mẫu báo cáo tài chính** khác nhau, không so sánh chỉ tiêu '
         'với doanh nghiệp thường được.', '',
         f'## 2. Lớp 1 — {len(rows_l1)} dòng', '',
         'Dòng `L4` thụt vào là ngoại lệ của nhánh ngay trên nó.', '',
         '| Cấp | Mã ICB | Tên nhánh ICB | → Ngành | Vì sao |', '|---|---|---|---|---|']
    for cap, code, nm, ind, note in rows_l1:
        pre = '⤷ ' if cap == 'L4' else ''
        m.append(f'| {cap} | {pre}`{code}` | {nm} | **{ind or "— không nạp"}** | {note} |')

    byind = {}
    for t, ind, why in OVERRIDE:
        byind.setdefault(ind, []).append((t, why))
    m += ['', f'## 3. Lớp 2 — {len(OVERRIDE)} dòng gán tay', '',
          'Xếp theo ngành. Mã nào cả lớp 1 lẫn phán đoán tay cùng một ngành thì **không có mặt ở đây** '
          '— đưa vào là đóng băng lớp 1, sửa map ICB về sau sẽ không lan tới được.', '']
    for code, _ in INDUSTRIES:
        g = byind.get(code)
        if not g:
            continue
        m += [f'### {code} — {names[code]} · {len(g)} mã', '',
              '| Mã | Doanh nghiệp | Vì sao đè |', '|---|---|---|']
        for t, why in sorted(g):
            m.append(f'| `{t}` | {ISSUER_NAME.get(t, "")} | {why} |')
        m.append('')

    open(os.path.join(here, 'industry-mapping.md'), 'w', encoding='utf-8').write(NL.join(m) + NL)
    open(os.path.join(here, 'industry-mapping.json'), 'w', encoding='utf-8').write(json.dumps({
        'do_ngay': DO_NGAY,
        'industries': [{'code': c, 'name_vi': n} for c, n in INDUSTRIES],
        'layer1': [{'icb_code': c, 'icb_level': int(cap[1]), 'icb_name': nm,
                    'industry_code': ind or None, 'note': note}
                   for cap, c, nm, ind, note in rows_l1],
        'layer2': [{'ticker': t, 'industry_code': i, 'reason': r} for t, i, r in OVERRIDE],
    }, ensure_ascii=False, indent=2) + NL)
    print(f'industry-mapping.md  : {len(rows_l1)} dong lop 1, {len(OVERRIDE)} dong lop 2')
    print(f'industry-mapping.json: {len(INDUSTRIES)} nganh')


if __name__ == '__main__':
    main()
